language: rust
dist: trusty
sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
  - 1.37.0
- stable
- beta
- nightly

script:
  - cargo build --verbose
  - export RUST_BACKTRACE=1
  - cargo test --all --verbose
  - cargo test --release --all --verbose
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      cargo bench --all --verbose;
    fi
